return {
  settings = {
    gopls = {
        codelenses = {
            test = true,
            gc_details = true,
            generate = true,
            run_govulncheck = true,
            tidy = true,
            upgrade_dependency = true,
            vendor = true,
          },
          buildFlags = { "-tags=e2e,integration" },
          gofumpt = true,
          completeUnimported = true,
          usePlaceholders = true,
          diagnosticsDelay = "250ms",
          staticcheck = true,
          hints = {
            assignVariableTypes = true,
            compositeLiteralFields = true,
            compositeLiteralTypes = true,
            constantValues = true,
            functionTypeParameters = true,
            parameterNames = true,
            rangeVariableTypes = true,
          },
          analyses = {
            recursiveiter = true,
            maprange = true,
            framepointer = true,
            modernize = true,
            nilness = true,
            hostport = true,
            gofix = true,
            sigchanyzer = true,
            stdversion = true,
            unreachable = true,
            unusedfunc = true,
            unusedparams = true,
            unusedvariable = true,
            unusedwrite = true,
            useany = true,
          },
      },
  },
}
