#!/bin/bash

SCRIPT=$(realpath -e "$0")
BASEDIR=$(dirname "$(dirname "$SCRIPT")")


CONFIG_LINKNAME="config"
STATUS_LINKNAME="status.sh"
CONFIG_FILENAME="sway-config"
STATUS_FILENAME="sway-status.sh"
SWAY_DIR="$HOME/.config/sway"
CONFIG_LINKPATH="$SWAY_DIR/$CONFIG_LINKNAME"
STATUS_LINKPATH="$SWAY_DIR/$STATUS_LINKNAME"
CONFIG_FILEPATH="$BASEDIR/$CONFIG_FILENAME"
STATUS_FILEPATH="$BASEDIR/$STATUS_FILENAME"

if [ -f "$CONFIG_LINKPATH" ]
	then rm "$CONFIG_LINKPATH"
fi
ln -s "$CONFIG_FILEPATH" "$CONFIG_LINKPATH"

if [ -f "$STATUS_LINKPATH" ]
	then rm "$STATUS_LINKPATH"
fi
ln -s "$STATUS_FILEPATH" "$STATUS_LINKPATH"

echo "script completed!"
